USE SCOMGER
GO

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[USP_ADM_USUARIO_DELETE]') AND type in (N'P', N'PC'))
    DROP PROCEDURE [dbo].[USP_ADM_USUARIO_DELETE]
GO

CREATE PROCEDURE USP_ADM_USUARIO_DELETE
    @IdUsuario VARCHAR(20)
AS
BEGIN
    SET NOCOUNT ON;

    DELETE FROM Usuarios
    WHERE IdUsuario = @IdUsuario;
END;
GO
